package eu.europa.op.eli.pillar4.helper;

import java.io.File;
import java.net.URL;

import com.beust.jcommander.Parameter;

import eu.europa.op.eli.pillar4.helper.cli.FileExistsValidator;

public class ArgumentsSomething2Pillar4 {
	
	@Parameter(
			names = { "-so", "--sitemapOutput" },
			description = "Path to the output directory where sitemap files will be generated",
			required = true
	)
	protected File outputSitemap;
	
	@Parameter(
			names = { "-su", "--sitemapBaseUrl" },
			description = "Base URL of ELIs that will be listed in the sitemap file. All ELIs in the sitemap MUST begin by this base URL.",
			required = true
	)
	protected URL baseUrl;
	
	@Parameter(
			names = { "-ao", "--atomOutput" },
			description = "Path to the output file where the Atom feed will be generated",
			required = true
	)
	protected File outputAtom;
	
	@Parameter(
			names = { "-ah", "--atomHeader" },
			description = "Path to the input Atom 'skeleton' file containing the Atom header information; this skeleton can be generated by another command.",
			required = true,
			validateWith = FileExistsValidator.class
	)
	protected File atomHeader;

	@Parameter(
			names = { "-au", "--atomUrl" },
			description = "Target Atom Feed URL. If set, a dct:relation attribute will be inserted in the sitemap file.",
			required = false
	)
	protected URL feedUrl;
	
	@Parameter(
			names = { "-ad", "--atomDays" },
			description = "The number of days to consider to include sitemap entries in the Atom feed. Entries updated since this number of days will be included. Defaults to 60.",
			required = false
	)
	protected int atomDays = 60;
	
	public File getOutputSitemap() {
		return outputSitemap;
	}

	public void setOutputSitemap(File outputSitemap) {
		this.outputSitemap = outputSitemap;
	}

	public File getAtomHeader() {
		return atomHeader;
	}

	public void setAtomHeader(File atomHeader) {
		this.atomHeader = atomHeader;
	}

	public URL getBaseUrl() {
		return baseUrl;
	}

	public void setBaseUrl(URL baseUrl) {
		this.baseUrl = baseUrl;
	}

	public URL getFeedUrl() {
		return feedUrl;
	}

	public void setFeedUrl(URL feedUrl) {
		this.feedUrl = feedUrl;
	}

	public File getOutputAtom() {
		return outputAtom;
	}

	public void setOutputAtom(File outputAtom) {
		this.outputAtom = outputAtom;
	}

	public void setAtomDays(int atomDays) {
		this.atomDays = atomDays;
	}

	public int getAtomDays() {
		return atomDays;
	}
	
}
